name: shooting_star_sudoku
description: "별똥별 조각 찾기라는 컨셉으로 아이들이 재밌게 할만한 스도쿠 게임 앱"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.1.2+1

environment:
  sdk: ^3.9.0

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  # 다국어 지원을 위한 공식 패키지
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

  # State Management
  provider: ^6.1.2

  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Advertising
  google_mobile_ads: ^5.1.0

  # Analytics (비활성화)
  # firebase_core: ^3.6.0
  # firebase_analytics: ^11.3.3

  # JSON handling
  json_annotation: ^4.9.0

  # Utilities
  shared_preferences: ^2.3.2
  path_provider: ^2.1.4
  package_info_plus: ^8.0.0

  # UI
  flutter_animate: ^4.5.0
  lottie: ^3.1.2

  # Splash screen
  flutter_native_splash: ^2.3.13

  # Audio
  audioplayers: ^6.1.0

  # Vibration
  vibration: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

  # Code generation
  build_runner: ^2.4.13
  json_serializable: ^6.8.0
  hive_generator: ^2.0.1

  # Icon generation
  flutter_launcher_icons: ^0.14.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # 코드 자동 생성을 활성화하는 부분
  generate: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/sounds/
    - assets/puzzles/
    - assets/animations/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package

# Flutter Launcher Icons configuration
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/Icon-App.png"
  adaptive_icon_background: "#FF6B9D"
  adaptive_icon_foreground: "assets/images/Icon-App.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/images/Icon-App.png"
    background_color: "#FF6B9D"
    theme_color: "#FF6B9D"
  windows:
    generate: true
    image_path: "assets/images/Icon-App.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/images/Icon-App.png"

# Flutter Native Splash configuration
flutter_native_splash:
  color: "#080C2B"
  image: assets/images/splash.png
  android: true
  ios: true
  web: true
  android_gravity: center
  ios_content_mode: center
  fullscreen: true
  image_dark: assets/images/splash.png
  color_dark: "#080C2B"
  android_12:
    image: assets/images/splash.png
    color: "#080C2B"
    icon_background_color: "#080C2B"
